version: "3"
services:
  dns:
    build: .
    restart: always
    volumes:
      - /tmp/ddns_updates:/tmp/ddns_updates
      - /var/dns/tinydns-data:/srv/dns/root/data
    ports:
      - "${DNS_BIND_IP}:53:53/tcp"
      - "${DNS_BIND_IP}:53:53/udp"

